# Generated by Django 5.2.7 on 2025-10-04 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentlistedshopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlistedshopitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_student_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
