# Generated by Django 5.2.7 on 2025-10-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studentlistedshopitem_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='delivery_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
