# Generated by Django 5.2.7 on 2025-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shoporder_delivery_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
