# Generated by Django 5.2.7 on 2025-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shoporder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
