# Generated by Django 5.2.7 on 2025-10-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentshoporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentshoporder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders2', to='core.studentlistedshopitem'),
        ),
    ]
